package com.odde.bbuddy.budget;

public enum BudgetCategoryTypes {
    BUDGET_CATEGORY_TYPE_WEEK,
//	BUDGET_CATEGORY_TYPE_FORTNIGHT,
	BUDGET_CATEGORY_TYPE_SEMI_MONTH,
	BUDGET_CATEGORY_TYPE_MONTH,
	BUDGET_CATEGORY_TYPE_QUARTER,
	BUDGET_CATEGORY_TYPE_SEMI_YEAR,
	BUDGET_CATEGORY_TYPE_YEAR,
}
